name: Pull_Request_Check
on:
  pull_request:
    types:
      [ edited, opened, ready_for_review, reopened, synchronize]
  workflow_dispatch:

jobs:
  check_pr_content:
    name: PR_Reviews
    runs-on: ubuntu-latest
    steps:
      - name: Check_For_Title_And_Desc
        uses: actions/github-script@v3
        with:
          script: |
            const theTitle = context.payload.pull_request.title
            const theDescription = context.payload.pull_request.body
            
            const isNotEmptyTitle = theTitle && theTitle.match(/\s/);
            const isNotEmptyDesc = theDescription && theDescription.match(/\s/);
            
            if (!isNotEmptyTitle || !isNotEmptyDesc) {
              console.error(`Invalid PR, Cant Be Blank!`);
              process.exit(1);
            }